#!/bin/bash

source ../settings/scripts/_common.sh 2>/dev/null || source _common.sh
source /usr/share/yunohost/helpers

app="$YNH_APP_INSTANCE_NAME"

ynh_print_info "Declaring files to be backed up..."
ynh_backup "$install_dir"
ynh_backup "$data_dir"
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup "/etc/systemd/system/$app.service"
ynh_backup "/etc/logrotate.d/$app"
ynh_backup "/etc/$app/"
ynh_backup "/var/log/$app/"
ynh_print_info "Backup declaration completed."
