#!/bin/bash
# shellcheck disable=SC1091
source _common.sh

ynh_script_progression --message="Stopping YTPod..."
ynh_systemctl --service="$app" --action=stop || true

yunohost service remove "$app" || true
ynh_config_remove_logrotate
ynh_config_remove_systemd
ynh_config_remove_nginx
ynh_safe_rm "$app_etc_dir"
