#!/bin/bash

source ../settings/scripts/_common.sh 2>/dev/null || source _common.sh
source /usr/share/yunohost/helpers

app="$YNH_APP_INSTANCE_NAME"

ynh_restore "$install_dir"
ynh_restore "$data_dir"
ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

yunohost service add "$app" --description="YouTube to podcast bridge" --log="/var/log/$app/$app.log" || true
ynh_restore "/etc/logrotate.d/$app"
ynh_restore "/etc/$app/"
ynh_restore "/var/log/$app/" || true

systemctl daemon-reload

chown -R "$app:$app" "$install_dir" "$data_dir" "/etc/$app" "/var/log/$app"
ynh_systemctl --service="$app" --action=start
ynh_systemctl --service=nginx --action=reload
